### ISSUE TITLE
Use backpack?

### ISSUE THREAD

**Issue by chessai** [andrewthad/vex#1]

**Comment by chessai** [comment]
actually, maybe not. all of the arrays here are PrimArray/MutablePrimArray. there's no cost to just having a single array type then, no?

**Comment by andrewthad** [comment]
I’ve actually got another library, not yet on github, where I backpackify all of the stuff that would be built on PrimArray. I’m planning on removing these specializations from this library soon.

**Comment by andrewthad** [comment]
This is now on github as `indexed-unboxed-array`.
